#!/bin/bash

# подавляем вывод dmesg во время работы скрипта
# echo 1 > /proc/sys/kernel/printk

apt install sudo dialog -y
apt install keyboard-configuration tzdata -y
#variables
TMPDIR=/var/tmp
SWITCH=/root/switchuser

# Functions
msg() {
    ALL_OFF="\e[1;0m"
    BOLD="\e[1;1m"
    GREEN="${BOLD}\e[1;32m"
      local mesg=$1; shift
      printf "${GREEN}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
 }


create_oem_install() {
    echo "$USER" > $TMPDIR/user
    echo "$PASSWORD" >> $TMPDIR/password
    echo "$PASSWORD" >> $TMPDIR/password
    echo "$ROOTPASSWORD" >> $TMPDIR/rootpassword
    echo "$ROOTPASSWORD" >> $TMPDIR/rootpassword
    msg "Установка пароля root..."
    passwd root < $TMPDIR/rootpassword 1> /dev/null 2>&1
    /usr/bin/vncpasswd -f <<<"$ROOTPASSWORD"$'\n'"$ROOTPASSWORD" > /root/.vnc/passwd 
    msg "Adding user $USER..."
    useradd -m -G sudo -s /bin/bash -U $(cat $TMPDIR/user) 1> /dev/null 2>&1
    msg "Установка полного имени на $FULLNAME..."
    chfn -f "$FULLNAME" $(cat $TMPDIR/user) 1> /dev/null 2>&1
    msg "Установка пароля для $USER..."
    passwd $(cat $TMPDIR/user) < $TMPDIR/password 1> /dev/null 2>&1
    /usr/bin/vncpasswd -f <<<"$PASSWORD"$'\n'"$PASSWORD" > /home/$USER/.vnc/passwd 
    sed -i "/^root/a $USER ALL=(ALL) ALL" /etc/sudoers
    msg "Применение системных настроек..."
    systemctl disable systemd-resolved.service 1> /dev/null 2>&1
    
    msg "Очистка установки от нежелательных файлов..."
    rm -rf /var/log/*
    
    # Удалить временные файлы на хосте
    rm -rf $TMPDIR/user $TMPDIR/password $TMPDIR/rootpassword
}


dpkg-reconfigure keyboard-configuration
dpkg-reconfigure tzdata
dpkg-reconfigure locales


# Использование диалогового окна для запроса пользовательского ввода для переменных
USER=$(dialog --clear --title "Завершить установку " \
	--inputbox "Введите имя пользователя:
(Имена пользователей могут быть только строчными)" 8 50 \
        3>&1 1>&2 2>&3 3>&-)

if [ ! -z "$USER" ]
then
FULLNAME=$(dialog --clear --title "Finish  Install" \
    --inputbox "Введите полное имя для $USER:" 8 50 \
        3>&1 1>&2 2>&3 3>&- \
	)
fi

if [ ! -z "$FULLNAME" ]
then
PASSWORD=$(dialog --clear --title "Finish  Install" \
    --insecure \
    --passwordbox "Enter Password for $USER (at least 6 characters):" 8 50 \
        3>&1 1>&2 2>&3 3>&- )
else 
	clear
	msg "Configuration aborted. Restarting OEM script..."
	sleep 5 && exec bash /root/firstrun
	#exit 1
fi

if [ ! -z "$PASSWORD" ]
then
LEN=${#PASSWORD}
stat=1
	if [[ "$LEN" -ge 6 ]]; then
		stat=$?
	else 
		clear
		msg "Password does not match minimum lenght of 6 characters. Restarting OEM script..."
		sleep 5 && exec bash /root/firstrun
	fi
fi

if [ ! -z "$PASSWORD" ]
then
CONFIRMPASSWORD=$(dialog --clear --title " Installer" \
	--insecure --passwordbox "Confirm Password for $USER:" 8 50 \
        3>&1 1>&2 2>&3 3>&- \
	)
else 
	clear
	msg "Configuration aborted. Restarting OEM script..."
	sleep 5 && exec bash /root/firstrun
	#exit 1
fi

if [[ "$PASSWORD" != "$CONFIRMPASSWORD" ]]; then
    clear
    msg "User passwords do not match! Restarting OEM script..."
    sleep 5 && exec bash /root/firstrun
    #exit 1
fi

if [ ! -z "$CONFIRMPASSWORD" ]
then
ROOTPASSWORD=$(dialog --clear --title "Finish  Install" \
    --insecure \
    --passwordbox "Enter Root Password (at least 6 characters):" 8 50 \
        3>&1 1>&2 2>&3 3>&- \
	)
else 
	clear
	msg "Configuration aborted. Restarting OEM script..."
	sleep 5 && exec bash /root/firstrun
	#exit 1
fi

if [ ! -z "$ROOTPASSWORD" ]
then
LEN=${#ROOTPASSWORD}
stat=1
	if [[ "$LEN" -ge 6 ]]; then
		stat=$?
	else 
		clear
		msg "Password does not match minimum lenght of 6 characters. Restarting OEM script..."
		sleep 5 && exec bash /root/firstrun
	fi
fi

if [ ! -z "$ROOTPASSWORD" ]
then
CONFIRMROOTPASSWORD=$(dialog --clear --title " Installer" \
	--insecure --passwordbox "Confirm Root Password:" 8 50 \
        3>&1 1>&2 2>&3 3>&- \
	)
else 
	clear
	msg "Configuration aborted. Restarting OEM script..."
	sleep 5 && exec bash /root/firstrun
	#exit 1
fi

if [[ "$ROOTPASSWORD" != "$CONFIRMROOTPASSWORD" ]]; then
    clear
    msg "Пароли Root не совпадают! Перезапуск OEM-скрипта..."
    sleep 5 && exec bash /root/firstrun
    #exit 1
fi

if [ ! -z "$CONFIRMROOTPASSWORD" ]
then
dialog --clear --title "Finish Ubuntu Install" \
    --yesno "Is the below information correct:
    Username = $USER
    Full Name for $USER = $FULLNAME
    Password for $USER = $PASSWORD
    Password for root = $ROOTPASSWORD" 20 50 \
    3>&1 1>&2 2>&3 3>&-
else
    clear
    msg "Configuration aborted. Restarting OEM script..."
    sleep 5 && exec bash /root/firstrun
    #exit 1
fi

response=$?
case $response in
   0) clear; msg "Proceeding....";;
   1) clear; msg "Configuration aborted. Restarting OEM script..."; sleep 5 && exec bash /root/firstrun;;
   255) clear; msg "Configuration aborted. Restarting OEM script..."; sleep 5 && exec bash /root/firstrun;;
esac

create_oem_install

msg "Настройка завершена. Уборка..."
# Здесь мы экспортируем отображаемую переменную для всех известных пользователей
echo "export DISPLAY=:1" >> /root/.bashrc && echo "export DISPLAY=:1" >> /home/$USER/.profile
touch /home/$USER/.hushlogin
# Здесь мы перезаписываем .bash_login, чтобы отменить первый запуск oem, и взлом, чтобы перенаправить пользователя после завершения установки oem.
echo "exec su - $USER" > $SWITCH 
echo "$SWITCH; exit" > /root/.bash_profile
chmod +x $SWITCH
if [ -e /etc/ssh/sshd_config ]
then
	sed -i s/"PermitRootLogin yes"/"#PermitRootLogin prohibit-password"/g /etc/ssh/sshd_config
fi
msg "Вы можете начать использовать недавно установленную версию Ubuntu"
# Замените текущее действие новой оболочкой для пользователя
exec su - $USER
