# Какой протокол использовать при выполнении операций git. Поддерживаемые значения: ssh, https
git_protocol: ssh
# Какой редактор gh следует запускать при создании задач, запросов на вытягивание и т. д. Если пусто, будет относиться к среде.
editor:
# Когда интерактивная подсказка. Это глобальная конфигурация, которую нельзя переопределить по имени хоста. Поддерживаемые значения: включено, отключено
prompt: enabled
# Программа пейджера для отправки вывода команды, например. "меньше". Установите значение «cat», чтобы отключить пейджер.
pager:
# Псевдонимы позволяют создавать псевдонимы для команд gh
aliases:
    co: pr checkout
    igrep: '!gh issue list --label="1" | grep "2"'
    v: repo view
    se: search repos
    clone: repo clone
    ls: repo list
    pv: pr view
    bugs: issue list --label=bugs
    homework: issue list --assignee @me
    epicsBy: issue list --author="1" --label="epic"
# Путь к unix-сокету, через который отправляются HTTP-соединения. Если пусто, HTTP-трафик будет обрабатываться net/http.DefaultTransport.
http_unix_socket:
# Какой веб-браузер должен использовать gh при открытии URL-адресов. Если пусто, будет относиться к окружающей среде.
browser:
