#!/data/data/com.termux/files/usr/bin/env bash
#
# exec w3m 'https://wiki.archlinux.org/title/installation_guide'
#
exec w3m 'https://wiki.archlinux.org/title/Installation_guide_(%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9)'


