#!/data/data/com.termux/files/usr/bin/zsh
#
# This is a termux-url-opener script to do diffrent tasks on my Android phone 
#
#
#
# How to use this script
#############################
# Create the bin directory
# ➜ ~ mkdir bin
# ➜ ~ cd bin
# Create the script (copy & paste) I use neovim. Use your prefered editor
# ➜ nvim termux-url-opener
# 
# Make it executable
# ➜ chmod +x termux-url-opener
# 
# Install zsh wget and ffmpeg
# ➜ pkg install zsh wget ffmpeg python
# https://wiki.termux.com/wiki/Shells
#
# Install youtube_dl and scdl with pip
# ➜ pip install youtube_dl
# ➜ pip install scdl mutagen
#
# run the following command to enable the termux storage features
# ➜ termux-setup-storage
# https://wiki.termux.com/wiki/Termux-setup-storage

url=$1
echo "Что мне делать с $url ?"
echo "y) загрузить видео с YouTube в папку с фильмами"
echo "u) загрузите видео с YouTube и конвертируйте его в mp3 (музыкальная папка)"
echo "s) скачать с scdl (soundcloud)"
echo "w) файл wget в папку загрузки" 
echo "d) lynx сохранение текста"
echo "g) git clone"
echo "x) ничего такого"

read CHOICE
case $CHOICE in
    y)
        youtube-dl -o "/storage/emulated/0/Movies/%(title)s.%(ext)s" $url
	;;
    u)
	echo "Artist"
	read artist
	echo "Title"
	read title
	echo "Album"
	read album
	youtube-dl --extract-audio --audio-format mp3 --output "/storage/emulated/0/Music/$artist-$title.%(ext)s" $url
	mid3v2 -a $artist -t $title -A $album /storage/emulated/0/Music/$artist-$title.mp3
	;;
    s)
	scdl -l $url --path /storage/emulated/0/Music
        echo "нужна работа"
	;;
    w)
        cd ~/storage/downloads
	wget $url
	;;
    x)
        echo "bye"
	;; 
    d)
        cd ~/Documents/dumps
        lynx -dump -nolist $url > "%(title)s.%(ext)s"
  ;;
    g)
        gh repo view $url
  ;;

esac
