#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'
    # установить тему spacevim. по умолчанию слой цветовой схемы не загружен,
    # если вы хотите использовать больше цветовых схем, пожалуйста, загрузите 
    # colorscheme layer
    colorscheme = "obsidian"
    colorscheme_bg = "dark"
    # Отключить гиколоры в базовом режиме, многие терминалы не поддерживают 24-битные
    # true colors
    enable_guicolors = true
    # Отключите разделитель строки состояния, если вы хотите использовать другое значение,
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    # disabled_plugins = ["markdown.vim"]
    bootstrap_after = 'bootstrap#after'
    filetree_direction  = 'left'
    sidebar_width = 35

[[layers]]
  name = 'sudo'

[[layers]]
  name = 'fzf'

[[layers]]
  name = "foldsearch"

[[layers]]
    name = 'git'
    git_plugin = 'git'
    git_diff_position = 'vsplit'

# [[layers]]
    # name = 'github'
    # github_access_token = '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'

# load the zettelkasten layer
[[layers]]
  name = "zettelkasten"
# load the fuzzy finder layer: telescope
[[layers]]
  name = "telescope"

[[layers]]
    name = 'colorscheme'

[[layers]]
    name = 'core'

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'bottom'
    default_height = 100
    enable_cursorword = true


[[layers]]
    name = "ui"
    enable_scrollbar = true
    enable_sidebar = true

[[layers]]
    name = "incsearch"

[[layers]]
    name = "lang#sh"
    
[[layers]]
    name = 'lang#vim'

[[layers]]
    name = 'lang#lisp'

[[layers]]
    name = 'lang#vue'

[[layers]]
    name = "lang#markdown"
    enabled_formater = ["remark", "prettier"]

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "format"
  # format_method = "codefmt"
  format_on_save = false
  # silent_format = true

[[layers]]
    name = 'lsp'
    enabled_clients = ['pyright']

[[layers]]
    name = "lang#python"
    enabled_linters = ['python', 'pylint']
    format_on_save = true
    # enable_typeinfo = true
    python_file_head = [
      '#!/data/data/com.termux/files/usr/bin/env python',
      '# -*- coding: utf-8 -*-',
      '',
      ''
  ]

[[layers]]
    name = 'lang#html'
    emmet_leader_key = "<C-e>"
    emmet_filetyps = ['html']

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = 'lang#rst'

[[layers]]
    name = 'mail'
    imap_host = 'imap.yandex.ru'
    imap_port = '993'
    imap_login = 'easy.quest'
    imap_password = 'rltjmccsqpioigud'

[[layers]]                                                
    name = 'tools#mpv'
    # mpv_interpreter = '/data/data/com.termux/files/usr/bin/mpv'
    musics_directory = '/sdcard/Music/Яндекс/Playlists'

[[layers]]
    name = 'tmux'
    tmux_navigator_modifier = "alt"
    enable_tmux_clipboard = true

[[layers]]
    name = "cscope"

[[layers]]
  name = "ctrlp"

[[layers]]
    name = 'telescope'
    enable = 'has("nvim")'

[[custom_plugins]]
    repo = 'abra/vim-obsidian'
    merged = false

[[custom_plugins]]
    repo = 'epwalsh/obsidian.nvim'
    merged = false    

[[custom_plugins]]
    repo = 'VincentCordobes/vim-translate'
    merged = false

[[custom_plugins]]
    repo = 'alker0/chezmoi.vim'
    merged = false

[[custom_plugins]]
    repo = 'dbeniamine/cheat.sh-vim'
    merged = false
   
# [[custom_plugins]]
    # repo = 'vimwiki/vimwiki'
    # merged = false

[[custom_plugins]]
  repo = 'liuchengxu/space-vim-dark'
  merged = false

[[custom_plugins]]
  repo = 'KabbAmine/lazyList.vim'
  merged = false

[[custom_plugins]]
  repo = 'scrooloose/syntastic'
  merged = false

[[layers]]
  name = "leaderf"

[[layers]]
    name = 'ssh'
    ssh_address = '193.176.78.86'
    ssh_user = 'zzz'
    ssh_port = '22'

[[layers]]
  name = "lang#go"

